spring:
  liquibase:
    change-log: classpath:/db/changelog-master.xml
  datasource:
    url: jdbc:postgresql://${NAUKA_DATABASE_HOST:localhost}:5432/nauka_db
    username: nauka_db
    password: nauka_db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
